### ISSUE TITLE
Feature Request: Python Client for Compress JSON

### ISSUE THREAD

**Issue by raunakdoesdev** [beenotung/compress-json#10]
Can help work on this if you want, but would love to see a Python version of this repository!

**Comment by beenotung** [comment]
The python implementation is completed and published to [pypi](https://pypi.org/project/compress-json-python/) :rocket: 

You can install it with
```bash
pip install compress-json-python
```

And import it with
```python
from compress_json import compress, decompress
```

Thank for your suggestion, feel free to re-open this issue if needed :)
