### ISSUE TITLE
Opening compressed JSON in python

### ISSUE THREAD

**Issue by Lservi** [beenotung/compress-json#15]
I'm trying to use the python library, but I can't figure out how should I open compressed json files. Can someone shed some light?

I saved a file like this, how can I open it later from another python script?

```
with open("data.json", "w") as fd:
	fd.write(json.dumps(compress(data)))
```

**Comment by beenotung** [comment]
Here's an example to write and read the compressed data with file

`write.py`:
```python
from compress_json import compress
import json

data = {
  'id': 1,
  'username': 'alice'
}

with open("data.json", "w") as fd:
  fd.write(json.dumps(compress(data)))
```

`read.py`:
```python
from compress_json import decompress
import json

with open("data.json", "r") as fd:
  print(decompress(json.load(fd)))
```

**Comment by beenotung** [comment]
Feel free to re-open this issue if you need further helps.
