### ISSUE TITLE
Depends on window object

### ISSUE THREAD

**Issue by latel88** [beenotung/compress-json#17]
https://github.com/beenotung/compress-json/blob/f90e5c8322f63e0c63d54d7c40d2c85202cf2894/src/browser.ts#L14
WebWorker cannot load the module because the above file depends on the window object.
Can you add a workaround?
Thanks

**Comment by beenotung** [comment]
You can import this package using commonjs / ESM convention, it is not depending on any DOM APIs.

The browser.ts is a wrapper for bundler to support vanilla js style usage in the browser environment.
