### ISSUE TITLE
How to know if a json is compressed?

### ISSUE THREAD

**Issue by Hedronmx** [beenotung/compress-json#20]
I have some old jsons that have not been compressed and I would like to program a logic that check if the json is compressed then decompress it else just return the original json.

Thanks!

**Comment by beenotung** [comment]
You can try to uncompress it in a try-catch block. If it fails to uncompress, you can return the original data.

**Comment by beenotung** [comment]
@Hedronmx does that work in your case?

**Comment by Hedronmx** [comment]
This works perfectly!! Thank you!
